"""Update User with Sync Statuses

Revision ID: 06aefed89494
Revises: 1a43ad43e5e3
Create Date: 2025-09-29 14:44:31.268917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aefed89494'
down_revision = '1a43ad43e5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sync_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('hubspot_sync_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('google_sync_completed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('hubspot_sync_completed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_sync_error', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hubspot_sync_error', sa.Text(), nullable=True))
    op.drop_column('users', 'gmail_sync_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_sync_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'hubspot_sync_error')
    op.drop_column('users', 'google_sync_error')
    op.drop_column('users', 'hubspot_sync_completed_at')
    op.drop_column('users', 'google_sync_completed_at')
    op.drop_column('users', 'hubspot_sync_status')
    op.drop_column('users', 'google_sync_status')
    # ### end Alembic commands ###