"""Remove summary from Document

Revision ID: 1a43ad43e5e3
Revises: d2d98780c8cd
Create Date: 2025-09-29 14:11:31.385150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a43ad43e5e3'
down_revision = 'd2d98780c8cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###