"""Allow sync for completed status to enable new email detection

Revision ID: 8510ffa0d17a
Revises: 06aefed89494
Create Date: 2025-09-29 17:34:01.848928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8510ffa0d17a'
down_revision = '06aefed89494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###