"""Simplify sync statuses

Revision ID: b38420f3e36b
Revises: 8510ffa0d17a
Create Date: 2025-09-30 10:57:20.889786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38420f3e36b'
down_revision = '8510ffa0d17a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###