"""Add gmail sync status to User

Revision ID: d2d98780c8cd
Revises: 89d80518fce4
Create Date: 2025-09-29 12:23:29.775263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d98780c8cd'
down_revision = '89d80518fce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add column with default value first, then update existing rows
    op.add_column('users', sa.Column('gmail_sync_status', sa.String(length=20), nullable=False, server_default='pending'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_sync_status')
    # ### end Alembic commands ###